name: Example Workflow

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Script
      run: |
        echo "Running script with API key..."
        # Replace this line with the command to run your script
      env:
        PLAYGROUND_API_KEY: ${{ secrets.PLAYGROUND_API_KEY }}
